apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namePrefix: prod-
resources:
- ../../base
#  - pvc.yaml
patchesStrategicMerge:
- configmap.yaml
- deployment.yaml
- ingress.yaml
images:
- name: choms0209/k8s-edu
  newTag: "202501231028"
- name: ydcho0902/k8s-edu
  newTag: "202501212323"
